### ISSUE TITLE
Remove calls to the api

### ISSUE THREAD

**Issue by lowlevelm** [ArchiveTeam/yahoogroups-grab#2]
Only grab the front-end page to avoid errors.

When a page is empty, it will have a line containing:
    GROUPS.API_ERROR_MSGS = {"message":{"e":1001,"s":500}};
If it has no errors, the line will contain
    GROUPS.API_ERROR_MSGS = [];

The grab script should fail the item unless "GROUPS.API_ERROR_MSGS = [];" is in the response body.

**Comment by marked** [comment]
It might not be easy to find those lines.  Can you link the two pages?

**Comment by lowlevelm** [comment]
The 0bin links where provided by DLoader.
Empty: https://0bin.net/paste/7kipISe+cSTfETg4#JFTG4T7Fg9OfoDZUaaDHjnftEiKTzJa2hNoD82mXW+v
Normal: https://0bin.net/paste/F4kHBaKKgyUeRxzG#0C2J6pX81tvlDc8IekQ6yVdGB3gIUKrWtGYC6VIrH+7
DLoader said the url was: https://groups.yahoo.com/neo/groups/21cfrpart11/conversations/messages/11775

**Comment by Arkiver2** [comment]
fixed with 092309871f47613ed9069ba2394cc81912851e05
