### ISSUE TITLE
Ignore more URLs that might cause bad data abort

### ISSUE THREAD

**Issue by Hanitus** [ArchiveTeam/yahoogroups-grab#3]
I lost my logs, but I got bad data error for https://groups.yahoo.com/neo/groups/$GROUP/files

I think you can safely ignore the following URLs. I didn't find any public group where you could access these. 

https://groups.yahoo.com/neo/groups/$GROUP/database
https://groups.yahoo.com/neo/groups/$GROUP/links/all
https://groups.yahoo.com/neo/groups/$GROUP/polls/open
https://groups.yahoo.com/neo/groups/$GROUP/events
https://groups.yahoo.com/neo/groups/$GROUP/files

Alternatively don't kill the job with bad data if these are returned (note the 307):

GROUPS.API_ERROR_MSGS = {"files":{"e":1101,"s":307}};
GROUPS.API_ERROR_MSGS = {"links":{"e":1101,"s":307}};
GROUPS.API_ERROR_MSGS = {"database":{"e":1101,"s":307}};
GROUPS.API_ERROR_MSGS = {"polls":{"e":1101,"s":307}};

Or just grab only: 

https://groups.yahoo.com/neo/groups/$GROUP/info
https://groups.yahoo.com/neo/groups/$GROUP/conversations/messages

**Comment by Arkiver2** [comment]
Thanks for the report!

**Comment by Arkiver2** [comment]
fixed with 60583667627523a1ecf967547293e4acaa5ead18
